export const GET_TRANSACTIONS_START = 'GET_TRANSACTIONS_START';
export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const GET_TRANSACTIONS_ERROR = 'GET_TRANSACTIONS_ERROR';

export const GET_TOTAL_AMOUNT_START = 'GET_TOTAL_AMOUNT_START';
export const GET_TOTAL_AMOUNT = 'GET_TOTAL_AMOUNT';
export const GET_TOTAL_AMOUNT_ERROR = 'GET_TOTAL_AMOUNT_ERROR';

export const SEND_XYM_START = 'SEND_XYM_START';
export const SEND_XYM = 'SEND_XYM';
export const SEND_XYM_ERROR = 'SEND_XYM_ERROR';

export const UPDATE_WALLET_SETTINGS = 'UPDATE_WALLET_SETTINGS';

export const CONFIRM_RECOVERY_PHRASE_START = 'CONFIRM_RECOVERY_PHRASE_START';
export const CONFIRM_RECOVERY_PHRASE = 'CONFIRM_RECOVERY_PHRASE';
export const CONFIRM_RECOVERY_PHRASE_ERROR = 'CONFIRM_RECOVERY_PHRASE_ERROR';

export const GET_RECOVERY_PHRASE_START = 'GET_RECOVERY_PHRASE_START';
export const GET_RECOVERY_PHRASE_ERROR = 'GET_RECOVERY_PHRASE_ERROR';
export const GET_RECOVERY_PHRASE = 'GET_RECOVERY_PHRASE';

export const RECOVER_WALLET = 'RECOVER_WALLET';
export const RECOVER_WALLET_START = 'RECOVER_WALLET_START';
export const RECOVER_WALLET_ERROR = 'RECOVER_WALLET_ERROR';
