export const ADD_CONNECTION_START = 'ADD_CONNECTION_START';
export const ADD_CONNECTION = 'ADD_CONNECTION';
export const ADD_CONNECTION_ERROR = 'ADD_CONNECTION_ERROR';

export const VERIFY_CONNECTION_START = 'VERIFY_CONNECTION_START';
export const VERIFY_CONNECTION = 'VERIFY_CONNECTION';
export const VERIFY_CONNECTION_ERROR = 'VERIFY_CONNECTION_ERROR';

export const DECLINE_CONNECTION_START = 'DECLINE_CONNECTION_START';
export const DECLINE_CONNECTION = 'DECLINE_CONNECTION';
export const DECLINE_CONNECTION_ERROR = 'DECLINE_CONNECTION_ERROR';
