const NAVIGATORS = {
  MAIN: 'NAVIGATORS_MAIN',
  SETTINGS: 'NAVIGATORS_SETTINGS',
  ROOT: 'NAVIGATORS_ROOT',
  CONNECTIONS: 'NAVIGATORS_CONNECTIONS',
  CREDENTIALS: 'NAVIGATORS_CREDENTIALS',
};

export default NAVIGATORS;
