const IMAGES = {
  DID_LOGO: require('../../assets/images/DID_LOGO_SMALL.png'),
  ACCEPTED: require('../../assets/images/Accepted_A.png'),
  BACK: require('../../assets/images/Backwards_Icon.png'),
  NEXT: require('../../assets/images/Next.png'),
  MAIN: require('../../assets/images/Main.png'),
  MAIN_ACTIVE: require('../../assets/images/Main_A.png'),
  CONNECTIONS: require('../../assets/images/Connections.png'),
  CONNECTIONS_ACTIVE: require('../../assets/images/Connections_A.png'),
  QR: require('../../assets/images/QR.png'),
  QR_ACTIVE: require('../../assets/images/QR_A.png'),
  SETTINGS: require('../../assets/images/Settings.png'),
  SETTINGS_ACTIVE: require('../../assets/images/Settings_A.png'),
  CREDENTIALS_ILLUSTRATION: require('../../assets/images/Credential_Illustration.png'),
  CONNECTIONS_ILLUSTRATION: require('../../assets/images/Connection_Illustration.png'),
  PROFILE_ILLUSTRATION: require('../../assets/images/Profile_Illustration.png'),
  NO_PHOTO_ICON: require('../../assets/images/No_Photo_Icon.png'),
  GEENS_ICON: require('../../assets/images/Geens_Icon.png'),
  NEM_ICON: require('../../assets/images/NEM_icon.png'),
  CIRCLE_PENDING: require('../../assets/images/Circle_Pending.png'),
  CIRCLE_DENIED: require('../../assets/images/Circle_Denied.png'),
  LOADING: require('../../assets/images/Loading_Icon.png'),
  CIRCLE_ACCEPTED: require('../../assets/images/Circle_Accepted.png'),
  SETTINGS_ICON: require('../../assets/images/Settings_icon.png'),
  SIGNOUT_ICON: require('../../assets/images/Signout_icon.png'),
  RECEIVE_ICON: require('../../assets/images/Receive_Icon.png'),
  IDENTIFICATION_ILLUSTRATION: require('../../assets/images/Identofy_Illustration.png'),
  VERIFIED_ILLUSTRATION: require('../../assets/images/Verified_Illustration.png'),
  PROVE_ILLUSTRATION: require('../../assets/images/Prove_Illustration.png'),
  BACKUP_ILLUSTRATION: require('../../assets/images/Backup_Illustration.png'),
  DOT_EMPTY: require('../../assets/images/Dot_Empty.png'),
  DOT_FILL: require('../../assets/images/Dot_Fill.png'),
  CLOSE: require('../../assets/images/Close_Icon.png'),
  ADD_NEW: require('../../assets/images/Add_New_icon.png'),
};

export default IMAGES;
