export const CREATE_CREDENTIAL = 'CREATE_CREDENTIAL';

export const SAVE_CREDENTIAL = 'SAVE_CREDENTIAL';

export const VERIFY_CREDENTIAL_START = 'VERIFY_CREDENTIAL_START';
export const VERIFY_CREDENTIAL = 'VERIFY_CREDENTIAL';
export const VERIFY_CREDENTIAL_ERROR = 'VERIFY_CREDENTIAL_ERROR';
