export const NAME_AND_SURNAME_UPDATE = 'NAME_AND_SURNAME_UPDATE';
export const ADDRESS_UPDATE = 'ADDRESS_UPDATE';
export const EMAIL_UPDATE = 'EMAIL_UPDATE';
export const BIRTH_DATE_UPDATE = 'BIRTH_DATE_UPDATE';
export const PHONE_UPDATE = 'PHONE_UPDATE';

export const PASSPORT_UPDATE_START = 'PASSPORT_UPDATE_START';
export const PASSPORT_UPDATE = 'PASSPORT_UPDATE';
export const PASSPORT_UPDATE_ERROR = 'PASSPORT_UPDATE_ERROR';

export const NATIONAL_ID_UPDATE_START = 'NATIONAL_ID_UPDATE_START';
export const NATIONAL_ID_UPDATE = 'NATIONAL_ID_UPDATE';
export const NATIONAL_ID_UPDATE_ERROR = 'NATIONAL_ID_UPDATE_ERROR';

export const DRIVING_LICENSE_UPDATE_START = 'DRIVING_LICENSE_UPDATE_START';
export const DRIVING_LICENSE_UPDATE = 'DRIVING_LICENSE_UPDATE';
export const DRIVING_LICENSE_UPDATE_ERROR = 'DRIVING_LICENSE_UPDATE_ERROR';

export const PROFILE_PHOTO_UPDATE_START = 'PROFILE_PHOTO_UPDATE_START';
export const PROFILE_PHOTO_UPDATE = 'PROFILE_PHOTO_UPDATE';
export const PROFILE_PHOTO_UPDATE_ERROR = 'PROFILE_PHOTO_UPDATE_ERROR';
