export const GET_ACCESS_TOKEN_START = 'GET_ACCESS_TOKEN_START';
export const GET_ACCESS_TOKEN = 'GET_ACCESS_TOKEN';
export const GET_ACCESS_TOKEN_ERROR = 'GET_ACCESS_TOKEN_ERROR';

export const AUTO_BACKUP_UPDATE = 'AUTO_BACKUP_UPDATE';
